tls:
  certificates:
    - certFile: "/etc/traefik/certs/openwebui.fzryzen.local.crt"
      keyFile: "/etc/traefik/certs/openwebui.fzryzen.local.key"

  stores:
    default:
      defaultCertificate:
        certFile: "/etc/traefik/certs/fzryzen.crt"
        keyFile: "/etc/traefik/certs/fzryzen.key"
