# ssl_certificates.yml
# This file is used to store the SSL certificates for the Traefik server.
# Simply add the certificates to the certs directory and update the paths below.

tls:
  certificates:
    - certFile: "/etc/traefik/certs/fzmacair.crt"
      keyFile: "/etc/traefik/certs/fzmacair.key"

  stores:
    default:
      defaultCertificate:
        certFile: "/etc/traefik/certs/fzmacair.crt"
        keyFile: "/etc/traefik/certs/fzmacair.key"
