# silverbullet.yml
# To support silverbullet, you need to run the silverbullet container with the following command:
# fzdocker silverbullet --persist
# And you need to include certificates in the certs directory.
http:
  routers:
    silverbullet:
      rule: "Host(`silverbullet.fzmacair.local`)"
      service: silverbullet-service
      middlewares:
        # Uncomment this to enable HTTPS redirection
        # - common-redirect-to-https

  services:
    silverbullet-service:
      loadBalancer:
        servers:
          - url: "http://fzsilverbullet:3000"
